[package]
name = "bruja"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pallet-contracts = "28.0.0"
pallet-contracts-primitives = "29.0.0"
