[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false

[tasks.docker-build]
command = "docker/build.sh"

[tasks.test-contract]
command = "cargo"
env = { "CONTRACTS_NODE" = "../../target/debug/node" }
args = ["test", "-p", "catalog", "--test", "e2e"]

[tasks.local-node]
script='''
cargo build -p node
./target/debug/node --dev --base-path ./local/$(uuidgen)
'''