[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
DOCKER_IMAGE = "bruja:latest"
DOCKER_BUILDER_IMAGE = "bruja_builder:latest"

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false

[tasks.start-colima]
script='''
colima start --memory 4 --cpu 4
'''

[tasks.docker-build]
script='''
docker build . -f docker/bruja_builder.Dockerfile -t $DOCKER_BUILDER_IMAGE
docker build .  \
    --build-arg BUILDER_IMAGE=$DOCKER_BUILDER_IMAGE \
    -f docker/bruja.Dockerfile \
    -t $DOCKER_IMAGE 
'''

[tasks.docker-up]
script='''
docker compose -f docker/compose.yml up -d
'''

[tasks.docker-down]
script='''
docker compose -f docker/compose.yml down
'''

[tasks.test-contract]
env = { "CONTRACTS_NODE" = "../../target/debug/node" }
script='''
cargo test -p catalog --test e2e
'''

[tasks.local-node]
script='''
cargo run -p node --dev --base-path ./test_dbs/$(uuidgen)
'''

[tasks.install-dev-dependencies]
script='''
cargo install --force --locked cargo-contract
cargo install subxt-cli
rustup target add wasm32-unknown-unknown
'''

# docker build --build-arg BUILDER_IMAGE=bruja_builder --target builder -t builder . -f docker/bruja.Dockerfile
# docker create --name temp-container builder
# docker cp foo:/dir/target test_dbs/target

# [tasks.cargo-build]
# script='''
# cross build --target x86_64-unknown-linux-musl --exclude scripts --workspace
# '''
# cargo contract build --manifest-path crates/catalog/Cargo.toml
