[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false

[tasks.docker-build]
command = "docker/build.sh"

[tasks.test-contract]
command = "cargo"
args = ["test", "--features", "e2e-tests"]

[tasks.local-node]
script='''
./target/debug/node start --dev --base-path ./local/$(uuidgen)
'''