[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
DOCKER_IMAGE = "bruja:latest"
DOCKER_BUILDER_IMAGE = "bruja_builder:latest"

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false

[tasks.start-colima]
script='''
colima start --memory 4 --cpu 4
'''

[tasks.docker-build]
script='''
docker build . -f docker/bruja_builder.Dockerfile -t $DOCKER_BUILDER_IMAGE
docker build .  \
    --build-arg BUILDER_IMAGE=$DOCKER_BUILDER_IMAGE \
    -f docker/bruja.Dockerfile \
    -t $DOCKER_IMAGE 
'''

[tasks.docker-up]
script='''
docker compose -f docker/compose.yml up -d
'''

[tasks.docker-down]
script='''
docker compose -f docker/compose.yml down
'''

[tasks.contract-tests]
env = { "CONTRACTS_NODE" = "../../target/debug/node" }
script='''
cargo test -p catalog --test contract-e2e
'''

[tasks.requester-worker]
script='''
cargo nextest run -p tests --test requester_worker --features integration_tests --retries 3
'''

[tasks.p2p-tests]
script='''
cargo nextest run -p tests --test p2p --features integration_tests --retries 5
'''

[tasks.local-node]
script='''
cargo run -p node -- --dev --base-path ./test_dbs/$(uuidgen)_local
'''

[tasks.install-dev-dependencies]
script='''
cargo install --force --locked cargo-contract
cargo install subxt-cli
cargo install cargo-nextest
rustup target add wasm32-unknown-unknown
rustup component add rust-src
'''

[tasks.cargo-build]
script='''
cargo contract build --manifest-path crates/catalog/Cargo.toml
cargo build --exclude scripts --exclude tests --workspace
'''
