[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false

[tasks.start-colima]
command = "colima start --memory 4 --cpu 4"

[tasks.test-contract]
command = "cargo"
env = { "CONTRACTS_NODE" = "../../target/debug/node" }
args = ["test", "-p", "catalog", "--test", "e2e"]

[tasks.local-node]
script='''
cargo build -p node
./target/debug/node --dev --base-path ./test_dbs/$(uuidgen)
'''

[tasks.install-dependencies]
script='''
cargo install --force --locked cargo-contract
cargo install subxt-cli
rustup target add wasm32-unknown-unknown
'''

[tasks.build]
script='''
cargo contract build --manifest-path crates/catalog/Cargo.toml ${@}
cargo build ${@}
'''