[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sp-runtime = { version = "34.0.0", default-features = false }
# sp-core = { version = "31.0.0", default-features = false }

# For Contract Config
pallet-contracts = { version = "30.0.0", default-features = false }

[features]
default = ["std"]
std = [
    # "sp-core/std",
    # "sp-runtime/std",
    "pallet-contracts/std",
]