services:
  node:
    image: $DOCKER_IMAGE
    container_name: node
    command: /usr/local/bin/node --dev --rpc-external
    expose:
      - 9944
    ports:
      - 0.0.0.0:9944:9944

  worker:
    image: $DOCKER_IMAGE
    container_name: worker
    command: sleep inf
    environment:
      - SURI=//Alice
      - ARTIFACT_FILE_PATH=catalog.contract