[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runtime = { path = "../runtime" }
clap = { version = "4.5.4", features = ["derive"] }
thiserror = "1.0.59"
serde_json = "1.0.117"

sp-core = { workspace = true }
sp-runtime = { workspace = true }

sc-service = { workspace = true }
sc-cli = "0.39.0"
