[package]
name = "utils"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
ink = { workspace = true }
ink_metadata = { version = "5.0.0" }
subxt = { workspace = true }
subxt-signer = { workspace = true, features = ["subxt"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
codec = { workspace = true }
pallet-contracts = { workspace = true, default-features = false }
sp-weights = { workspace = true, default-features = false }

sp-core = { workspace = true }

sp-runtime = { version = "34.0.0", default-features = true }
contract-extrinsics = "4.1.1"
rand = "0.8.5"

[features]
default = ["std"]
std = [
	"pallet-contracts/std",
]