[package]
name = "foo"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ink_e2e = "5.0.0"
tokio = { version = "1.37.0", features = ["fs"] }
subxt = { version = "0.35.3" }
wabt = "0.10.0"
subxt-signer = "0.35.3"
