[package]
name = "foo"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contract = { workspace = true}
tokio = { version = "1.37.0" , features = ["rt-multi-thread", "fs", "io-util"]}
subxt = { version = "0.35.3" }
subxt-signer = "0.35.3"
rand = "0.8.5"
