---
name: CI 

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          target:  wasm32-unknown-unknown
          cache-workspaces: true
          toolchain: 1.77

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      
      - name: Add Rust Deps
        shell: bash
        run: |
          rustup component add rust-src --toolchain 1.77-x86_64-unknown-linux-gnu
          rustup component add clippy --toolchain 1.77-x86_64-unknown-linux-gnu

      - name: Add Cargo Make
        shell: bash
        run: |
          cargo install --no-default-features --force cargo-make

      - name: Add Cargo Contract
        shell: bash
        run: |
          cargo install --force --locked cargo-contract

      - name: Add OS Dependencies
        shell: bash
        run: |
          sudo apt install -y protobuf-compiler

      - name: Cargo Build
        shell: bash
        run: |
          cargo make cargo-build

      - name: Unit Tests
        shell: bash
        run: cargo test

      - name: Contract Integration Tests
        shell: bash
        run: cargo make test-contract


