---
name: CI 

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
          # restore-keys: ${{ runner.os }}-cargo-

      - name: Install Deps
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler 

      - name: Add Rust Component
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          rustup component add rust-src

      - name: Add Cargo Tooling
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cargo install --no-default-features cargo-make
          cargo install --force --locked cargo-contract

      - name: Cargo Build
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          cargo make cargo-build

      - name: Unit Tests
        shell: bash
        run: |
          rustup component add clippy
          cargo test

      - name: Contract Integration Tests
        shell: bash
        run: cargo make test-contract



